theme: jekyll-theme-minimal
title: Chengxuan (Sheldon) Xia
github: is\_project\_page:false
![Image text](https://github.com/chengxuan-xia/chengxuan-xia.github.io/blob/main/%E5%A4%B4%E5%83%8F_lkn.jpg) 
